

services:
  # unifi-cam-driveway:
  #   container_name: unifi-cam-driveway
  #   restart: unless-stopped
  #   build: .
  #   volumes:
  #     - "./client.pem:/client.pem"
  #   command: >-
  #     unifi-cam-proxy
  #     --verbose.   
  #     --host 192.168.1.1.  
  #     --mac 'BB:BB:CC:33:44:CC'
  #     --ip 192.168.254.1
  #     --cert /client.pem
  #     --token "0LriwCvqsojSOnUfflyzVZ8FTf535EWb"
  #     --name "Driveway"
  #     --model "UVC G4 Dome"
  #     --fw-version "4.69.55"
  #     frigate
  #     --timestamp-modifier 90
  #     --snapshot-url "http://192.168.1.3:5000/api/driveway/latest.jpg"
  #     --ffmpeg-args='-c:v copy -c:a copy'
  #     --frigate-camera driveway
  #     --mqtt-host 192.168.1.3
  #     --mqtt-prefix frigate
  #     -s rtsp://192.168.1.3:8554/driveway_src

  unifi-cam-test:
    container_name: unifi-cam-test
    restart: unless-stopped
    build: .
    volumes:
      - "./client.pem:/client.pem"
    command: >-
      unifi-cam-proxy
      --verbose
      --host 192.168.1.1
      --mac 'DD:BB:CC:33:44:CC'
      --ip 192.168.254.1
      --cert /client.pem
      --token "kMGMrT4XHoJFLjn8JOKGMbxPdLEyka2n"
      --name "Driveway"
      --model "UVC G4 Dome"
      --fw-version "4.69.55"
      frigate
      --timestamp-modifier 90
      --snapshot-url "http://192.168.1.3:5000/api/test_cam/latest.jpg"
      --ffmpeg-args='-c:v copy -c:a copy'
      --frigate-camera test_cam
      --mqtt-host 192.168.1.3
      --mqtt-prefix frigate
      -s rtsp://192.168.1.3:8554/test_cam_src

